name: haskinote
channels:
  - huggingface
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - abseil-cpp=20211102.0
  - aiofiles=23.1.0
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - altair=5.0.1
  - anyio=3.7.0
  - arrow-cpp=11.0.0
  - async-timeout=4.0.2
  - attrs=23.1.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - boost-cpp=1.82.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - click=8.1.3
  - colorama=0.4.6
  - contourpy=1.0.7
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cudatoolkit=11.6.0
  - cycler=0.11.0
  - dataclasses=0.8
  - datasets=2.12.0
  - dill=0.3.6
  - exceptiongroup=1.1.1
  - fastapi=0.96.0
  - ffmpeg=4.3
  - ffmpy=0.3.0
  - filelock=3.12.0
  - fonttools=4.39.4
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.5.0
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.5.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - gradio=3.23.0
  - grpc-cpp=1.46.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=0.17.2
  - httpx=0.24.1
  - huggingface_hub=0.15.1
  - hyperframe=6.0.1
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.17.3
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcurl=7.87.0
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libhwloc=2.9.1
  - libiconv=1.17
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libnghttp2=1.46.0
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libstdcxx-ng=13.1.0
  - libtasn1=4.19.0
  - libthrift=0.15.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.11.4
  - libzlib=1.2.13
  - linkify-it-py=2.0.0
  - llvm-openmp=16.0.5
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib-base=3.7.1
  - mdit-py-plugins=0.3.3
  - mdurl=0.1.0
  - mkl=2022.2.1
  - multidict=6.0.4
  - multiprocess=0.70.14
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - ninja=1.11.1
  - numpy=1.24.3
  - openh264=2.1.1
  - openssl=1.1.1u
  - orc=1.7.4
  - orjson=3.9.0
  - packaging=23.1
  - pandas=2.0.2
  - pillow=9.4.0
  - pip=23.1.2
  - pkgutil-resolve-name=1.3.10
  - pyarrow=11.0.0
  - pycparser=2.21
  - pydantic=1.10.8
  - pydub=0.25.1
  - pyparsing=3.0.9
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-dotenv=1.0.0
  - python-multipart=0.0.6
  - python-tzdata=2023.3
  - python-xxhash=3.2.0
  - python_abi=3.9
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2023.3
  - pyyaml=6.0
  - re2=2022.04.01
  - readline=8.2
  - regex=2023.6.3
  - requests=2.31.0
  - responses=0.18.0
  - sacremoses=0.0.53
  - semantic_version=2.10.0
  - sentencepiece=0.1.99
  - setuptools=67.7.2
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.10
  - sniffio=1.3.0
  - sqlite=3.42.0
  - starlette=0.27.0
  - tbb=2021.9.0
  - tk=8.6.12
  - toolz=0.12.0
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm=4.65.0
  - transformers=4.28.1
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - uc-micro-py=1.0.1
  - unicodedata2=15.0.0
  - urllib3=2.0.2
  - utf8proc=2.6.1
  - uvicorn=0.22.0
  - websockets=11.0.3
  - wheel=0.40.0
  - xxhash=0.8.1
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.9.2
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - accelerate==0.19.0
      - av==10.0.0
      - charset-normalizer==3.1.0
      - cmake==3.26.3
      - coloredlogs==15.0.1
      - ctranslate2==3.14.0
      - faster-whisper==0.6.0
      - flatbuffers==23.5.26
      - humanfriendly==10.0
      - lit==16.0.5.post0
      - mpmath==1.3.0
      - networkx==3.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - onnxruntime==1.15.0
      - peft==0.3.0
      - protobuf==4.23.2
      - psutil==5.9.5
      - sympy==1.12
      - tokenizers==0.13.3
      - torch==2.0.1
      - triton==2.0.0
